# Group Registro
## Formulario de Registro [/registro/:idCliente]
###  Registrarte[POST]
+ Request 200 (application/json)
    Location : /registro/1
    + Body
        {        
            "nombre_usuario" : "Franco",
            "apellido_usuario" : "Di Leo",
            "mail_usuario" : "dileo.francoj@gmail.com",
            "telefono_usuario" : "1122334455",
            "password_usuario" : "1234"
        }
    
+ Response 200 (application/json)
   + Body
        {
            status: "ok",
            message: "Se envio un correo a tu cuenta de mail"
        }

# Group Login
## Formulario Login Usuario [/auth/login/:idCliente]
###  Login Usuario [POST]
+ Request 200 (application/json)
    Location : /auth/login/1
    + Body
        {        
            "mail" : "dileo.francoj@gmail.com",
            "password" : "1234"
        }
    
+ Response 200 
    + Body    
        {
            usuario:  {
                "id": 1
            },
            JWT: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9"
        }

# Group Carrito
## Vista Carrito [/carrito/:idCliente]
### Ver Carrito[GET]     
+ Request 200 
    Location : /carrito/1
    + Headers 
    {
        Authorization: Bearer eyJXXXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
    }
    
  
+ Response 200 (application/json)
   + Body
    {
        "status": "ok",
        "data": [
            {
                "id_carrito": 4,
                "id_usuario_carrito": 1,
                "id_compra_carrito": null,
                "id_producto_carrito": 16,
                "fecha_carrito": "2019-10-14T20:08:17.000Z",
                "id_producto": 16,
                "id_cliente_producto": 1,
                "nombre_producto": "CHAIN DR",
                "descripcion_producto": "Cadena para sectores exclusivos",
                "foto_producto": "fotochain.png",
                "visibilidad_producto": 1,
                "precio_producto": 4201,
                "stock_producto": 10
            }]
    }    

## Cargar Producto al Carrito [/carrito/:idCliente]
###  Cargar Producto[POST]     
+ Request 200 
    Location : /carrito/1
    + Headers 
        {   
            Content-Type: application/json
            Authorization: Bearer eyJXXXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
        }
    + Body
        {        
            "id_producto" : 16,
        }
+ Response 200 (application/json)
   + Body
    {
        "status": "ok",
        "data": 6
    }
    

## Cerrar Carrito [/compra/:idCliente]
###  Cerrar Carrito[POST]     
+ Request 200 
    Location : /compra/1
    + Headers 
        {   
            Authorization: Bearer eyJXXXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
        }
+ Response 200 (application/json)
    {
        "status": "ok",
        "url" : "LA URL QUE ME REDIRIGIRA A MERCADOPAGO??"
    }
    
# Group Productos
## Vista Productos [/productos/:idCliente]
### Lista Productos[GET] 
Location : /productos/1    
+ Request 200
    
+ Response 200 (application/json)
   + Body
    {
        "status": "ok",
        "data": [
            {
                "id_producto": 16,
                "id_cliente_producto": 1,
                "nombre_producto": "CHAIN DR",
                "descripcion_producto": "Cadena para sectores exclusivos",
                "foto_producto": "fotochain.png",
                "visibilidad_producto": 1,
                "precio_producto": 4201,
                "stock_producto": 10
            }]
    }    

## Producto Especifico [/productos/:idCliente/:idProducto]
### Producto Especifico [GET]     
+ Request 200 
    + Headers
        {
            Location : /productos/1/16   
         }
+ Response 200 (application/json)
   + Body
    {
        "status": "ok",
        "data":{      
                "id_producto": 16,
                "id_cliente_producto": 1,
                "nombre_producto": "CHAIN DR",
                "descripcion_producto": "Cadena para sectores exclusivos",
                "foto_producto": "fotochain.png",
                "visibilidad_producto": 1,
                "precio_producto": 4201,
                "stock_producto": 10
            }
    }    
   
# Group Usuario
## Indormacion del Usuario [/usuarios]
### Info Usuario[GET]   
+ Request 200 
    + Headers 
        {   
            Authorization: Bearer eyJXXXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
        }
+ Response 200 (application/json)
    + Body
        {
            "status": "ok",
            "data": [
                {
                    "nombre_usuario": "Franco",
                    "apellido_usuario": "Di Leo",
                    "telefono_usuario": "1144739222",
                    "mail_usuario": "dileo.francoj@gmail.com"
                }
            ]
        }

## Historial de Compra del Usuario [/usuarios/historial]
### Historial de Compra[GET]   
+ Request 200 
    + Headers 
        {   
            Authorization: Bearer eyJXXXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
        }
+ Response 200 (application/json)
    + Body
    {
        "status": "ok",
        "data": [
            {
                "id_compra": 1,
                "monto_compra": 12603,
                "fecha_compra": "0000-00-00 00:00:00"
            }
        ]
    }     

## Actualizar Perfil [/changedatos/:idCliente]
### Actualizar Perfil [PUT]   
+ Request 200 
    Location : /changepassword/1
    + Headers 
        {   
            Authorization: Bearer eyJXXXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
        }
+ Response 200 (application/json)
    + Body
        {
            "status": "ok"
        }    

## Actualizar Contraseña [/changepassword/:idCliente]
### Actualizar Contraseña [PUT]   
+ Request 200 
    Location : /changepassword/1
    + Headers
        {   
            
            Authorization: Bearer eyJXXXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
        }
+ Response 200 (application/json)
    + Body
        {
            "status": "ok"
        }         