#Group Productos Usuarios
##  Todos los Productos [/productos]
### Listado de todos los productos [GET]

+ Response 200
    Location 

+ Response 200 (application/json)
    [
        {
            status: 'ok',
            data : [
                {
                    nombre_p : "vino",
                    descripcion_p : "vino_descripcion",
                    precio_p: 270,
                    stock_p : 123123,
                    imagen_p : '/images/foto.jpg'
                }
            ]
        }
    ]