# Group Productos

## Todos los productos [/productos]
### Listado Productos [GET]
+ Request 200
    Location : /productos

+ Response 200 (application/json)

        [
            {
                
                "status": "ok",
                "choices": [
                    {
                        "nombre_p": "Vino",
                        "descripcion_p": "Descripcion producto",
                        "precio_p": 2000,
                        "stock_p" : 12,
                        "imagen_p" : "/images/vino.png"
                    }
                ]
            }
        ]



## Get producto [/productos/1]
### Producto Espesifico [GET]
+ Request 200 (application/json)
    Location : /productos/1
+ Response 200 (application/json)
    {
        nombre_p : "vino",
        precio_p : 142,
        stock_p : 3,
        descripcion_p : "vino rico",
        imagen_p : "/images/vino.jpg"
    }

# Group ProductosAdmin
## Eliminar producto [/productosAdmin/1]
### Borrar producto [DELETE]

+ Request 200 (application/json)
    Location : /productosAdmin/1
+ Response 200 (application/json)
    {
        status : 'ok'
    }



## Insert de productos [/productosAdmin]
### Cargar Producto [POST]
+ Request 200 (application/json)
    + Body
        {
            nombre_p : "Vino", 
            descripcion_p : "Descripcion del vino", 
            precio_p : 146,
            stock_p : 15, 
            imagen_p : "/images/vino.jpg"
        }
    
+ Response 200 (application/json)
   + Body
        {
            "status": "ok",
            "id_p" : 5
        }
## Put Producto [/productosAdmin]
### Actualizar Producto [PUT]
+ Request 200 (application/json)
    Location : /productosAdmin/1
    + Body
        {
            nombre_p : "vino",
            descripcion_p : "descripcion del vino",
            precio_p : 145,
            stock_p : 16,
            imagen_p : "images/vino.jpg"
        }
+ Response 200 (application/json)
    + Body
        {
            status : 'ok'
        }


# Group Usuarios
## Todos los usuarios [/usuarios]
### Listado Usuarios [GET]
+ Request 200
    Location : /usuarios

+ Response 200 (application/json)

        [
            {
                
                "status": "ok",
                "choices": [
                    {
                        "id_u": 1,
                        "mail_u": "dileo.francoj@gmail.com",
                        "password_u": "7110eda4d09e062aa5e4a390b0a572ac0d2c0220",
                        "nombre_u" : "Franco",
                        "apellido_u" : "Di Leo"
                        "codigo_confirmacion": "abcdefghi",
                        "cuenta_confirmada": 0
                    }
                ]
            }
        ]

# Group Registro
## Formulario de Registro [/registro]
###  Resgistrarte[POST]
+ Request 200 
    + Body
        {
            mail_u: "dileo.francoj@gmail.com",
            password_u: "1234",
            nombre_u : "Franco",
            apellido_u : "Di Leo",
        }
    
+ Response 200 (application/json)
   + Body
        {
            status: "ok",
            id : "true",
            message: "Confirmar la cuenta para iniciar sesion"
        }

## Confirmar Cuenta [/registro]
###  Confirmar Cuenta [GET]
+ Request 200 (application/json)
    Location : /registro/ffb38e65-7e86-4447-989d-61a0ee2d612f

    
+ Response 200 (application/json)
   + Body
        {
            estado:"cuenta confirmada"
        }


# Group Login
## Login Usuario [/auth]
###  Login Usuario[POST]
+ Request 200 (application/json)
    + Body
        {
            mail: "dileo.francoj@gmail.com",
            password: "1234",
        }
    
+ Response 200 (application/json)
   + Body
        {
            nombre: "dileo",
            JWT: "token 025160231523.5613.69653"
        }

## Login Administrador [/admin/login]
###  Login Administrador [POST]
+ Request 200 (application/json)
    + Body
        {
            mail: "dileo.francoj@gmail.com",
            password: "1234",
        }
    
+ Response 200 (application/json)
   + Body
        {
            nombre: "dileo",
            JWT: "token 025160231523.5613.69653"
        }
